elfin3:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  # Position Controllers ---------------------------------------
  joint1_position:
    type: position_controllers/JointPositionController
    joint: elfin_joint1

  joint2_position:
    type: position_controllers/JointPositionController
    joint: elfin_joint2

  joint3_position:
    type: position_controllers/JointPositionController
    joint: elfin_joint3

  joint4_position:
    type: position_controllers/JointPositionController
    joint: elfin_joint4

  joint5_position:
    type: position_controllers/JointPositionController
    joint: elfin_joint5

  joint6_position:
    type: position_controllers/JointPositionController
    joint: elfin_joint6

